### ISSUE TITLE
Url being redirected

### ISSUE THREAD

**Issue by joshbnntt** [hotwired/hotwire-site#17]
I'm not sure of the best way to contact you about this question. It seems like the hotwire.dev url is being redirected to the adl website to a post about the pyramid of hate. Is this intentional?

![Screenshot_20210706-083732](https://user-images.githubusercontent.com/8769725/124610662-51fbf880-de36-11eb-90df-1bf2ea592acb.png)

**Comment by dhh** [comment]
The project has been moved to a new URL: https://hotwired.dev.
