### ISSUE TITLE
Remove Strada until there is a release candidate?

### ISSUE THREAD

**Issue by swanson** [hotwired/hotwire-site#33]
:wave: Just wanted to share some friendly community feedback: people get very confused about Turbo Native and Strada. People that follow along closely are aware that you can use Turbo Native right now without Strada, but seeing Strada on the documentation site (with the "premiering in 202X" tag) causes people to think that you can't/shouldn't use Hotwire for mobile until it is released.

https://twitter.com/daniloassisjr/status/1613679182839484417
https://twitter.com/andrewculver/status/1357667191290810372
https://twitter.com/crohr/status/1385504977179881472
https://twitter.com/thisisdylandev/status/1447276418660982795
https://twitter.com/Its_stolt/status/1443936623746424832

Would you consider removing the mentions until there is a release candidate for Strada? @dhh

**Comment by KonnorRogers** [comment]
+1. I'm Definitely confused by what Strada is / does and it adds more indirection than clarity.

**Comment by gedw99** [comment]
its native gui with html aspects. Basically its a web view i think.

**Comment by dhh** [comment]
We're getting close now with Strada. @jayohms is putting the final touches on the first public release. So let's just update it with that when it ships.

Jay will be presenting Strada at Rails World.
